version: '3.3'

services:
  db:
    image: postgres:10.1-alpine
  backend:
    build: .
    image: whereis/backend:latest
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

