# Generated by Django 4.0.4 on 2022-05-23 08:01

from django.db import migrations, models
import django.db.models.deletion
import django_jsonform.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True)),
                ('clues', django_jsonform.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), null=True, size=4)),
                ('cards', django_jsonform.models.fields.ArrayField(base_field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(max_length=20), size=4), size=20)),
                ('answer', django_jsonform.models.fields.ArrayField(base_field=django_jsonform.models.fields.ArrayField(base_field=models.IntegerField(), size=2), size=4)),
                ('suggested_num_cards', models.IntegerField(null=True)),
                ('author', models.CharField(blank=True, max_length=50)),
                ('daily_set_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BoardClientState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField()),
                ('client_id', models.CharField(max_length=50)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.board')),
            ],
        ),
    ]
