# Generated by Django 2.0 on 2018-01-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='last_updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
