# Generated by Django 4.0.4 on 2022-06-24 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_board_adult'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('words', models.TextField(blank=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True)),
                ('adult', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='word_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.wordlist'),
        ),
    ]
